### ISSUE TITLE
Advance setup ordering seems a bit odd

### ISSUE THREAD

**Issue by carlosperate** [UDOOboard/Docs#1]
Hi,

I was going to submit a pull request with minor formatting and punctuation corrections to some of the Documentation, and I noticed that the articles in the https://github.com/UDOOboard/Docs/tree/master/docs/03_Advanced_Setup don't quite follow the pattern I would have expected. The current sorting is:

```
    00_Create_A_Bootable_MicroSD_Card_From_Preinstalled_Binaries.md
    01_Create_A_Bootable_MicroSD_Card_From_Sources.md
    02_Compile_Android_From_Sources.md
    02_UDOO_Kernel_Update_Procedure.md
    03_UDOO_Boot_From_SATA.md
    04_UDOO_Kernel_Update_Procedure.md
    04_UDOO_Usb_Debug.md
    05_UDOO_Usb_Debug.md
```

The following files are duplicates:

```
    02_UDOO_Kernel_Update_Procedure.md
    04_UDOO_Kernel_Update_Procedure.md
```

```
    04_UDOO_Usb_Debug.md
    05_UDOO_Usb_Debug.md
```

And I cannot find the article for [Compile_The_Linux_Kernel_And_The_Modules](http://www.udoo.org/docs/Advanced_Setup/Compile_The_Linux_Kernel_And_The_Modules). Although the same information is contained within the [01_Create_A_Bootable_MicroSD_Card_From_Sources.md](https://github.com/UDOOboard/Docs/blob/e1efcb8528a94ca8318d89b9dfc94b5f8f848c0e/docs/03_Advanced_Setup/01_Create_A_Bootable_MicroSD_Card_From_Sources.md#compile-the-kernel-and-the-modules) file.

Has a bad merge messed up these articles? Is there an actual file just for Compile_The_Linux_Kernel_And_The_Modules? Is it meant to just be a copy/paste from the section in 01_Create_A_Bootable_MicroSD_Card_From_Sources?

I could submit a pull request with the small corrections and the following sorting (following the currently published documentation from the website), but I though I should ask here first to see if there is an specific direction or format you'd like to follow:

```
    00_Create_A_Bootable_MicroSD_Card_From_Preinstalled_Binaries.md
    01_Create_A_Bootable_MicroSD_Card_From_Sources.md
    02_Compile_The_Linux_Kernel_And_The_Modules.md
    03_Compile_Android_From_Sources.md
    04_UDOO_Boot_From_SATA.md
    05_UDOO_Kernel_Update_Procedure.md
    06_UDOO_Usb_Debug.md
```

**Comment by carlosperate** [comment]
For reference: https://github.com/UDOOboard/Docs/compare/master...carlosperate:advance_setup?expand=1

**Comment by carlosperate** [comment]
any feedback?

**Comment by UDOOboard** [comment]
Thanks,

we followed you comment 

Regards,
UDOO Team
