### ISSUE TITLE
When I received UDOO-NEO-VK-7T, I cannot dispaly it.

### ISSUE THREAD

**Issue by oneway3124** [UDOOboard/Docs#3]
When I received UDOO-NEO-VK-7T, I cannot dispaly it.Why ?
Can you supply some guide docs for this? Thanks!

**Comment by UDOOboard** [comment]
here you can the guide docs:
http://www.udoo.org/docs-neo/Hardware_&_Accessories/LVDS.html

_------------------------------Maurizio CaporaliCEO[image: UDOO]
http://www.udoo.org/ Email maurizio.caporali@aidilab.it
maurizio.caporali@aidilab.itCell. +39 3939152067website
http://www.aidilab.com/  |  facebook
http://www.facebook.com/aidilab  |  twitter
http://twitter.com/AidilabSrl  |  google+
https://plus.google.com/u/0/b/112408342393715285021/+Aidilab/posts   Note
Confidenziali:  Le informazioni contenute in questa comunicazione e gli
eventuali documenti allegati hanno carattere confidenziale e sono ad uso
esclusivo del destinatario. Nel caso questa comunicazione Vi sia pervenuta
per errore, Vi informiamo che la sua diffusione e riproduzione è contraria
alla legge e preghiamo di darci prontamente avviso e di cancellare quanto
ricevuto.Confidentiality Note:  This e-mail message and any files
transmitted with it contain confidential information intended only for the
person(s) to whom it is addressed. If you are not the intended recipient,
you are hereby notified that any use or distribution of this e-mail is
strictly prohibited, please notify the sender and delete the original
message._

**Comment by oneway3124** [comment]
Please check your guide docs, use the lastest uEnv.txt of newest image, having the different contents.
For newer, this is not one step by stey guide, for it have some confuse.
Thanks you for your confirmation later.

**Comment by oneway3124** [comment]
Hi udoo board,

I have fixed this issue now, your docs maybe only been used for UDOObuntu_neo_v2.0beta5, not for UDOObuntu_neo_v2.0rc1. I think you should describe it in detail.
